//model class for our monthly expense
//this will be used to represent the data in our app and to interact with the database

class MonthlyExpense{
  //the fields our monthly expense object will have
  final int? id;//id is nullable because it will be auto-generated by the database when we insert a new record
  final String expenseName;
  final String expenseAmount;
  final String expenseCategory;

  //constructor for the model in memory
  MonthlyExpense({
    this.id,
    required this.expenseName,
    required this.expenseAmount,
    required this.expenseCategory,
  });

  //method to convert the model to a map for storage in the database
  Map <String, dynamic> toMap() {
    return{
      'expense_id' : id,
      'expense_name' : expenseName,
      'expense_amount' : expenseAmount,
      'expense_category' : expenseCategory,
    };
  }

  //rebuild the model from a map retrieved from the database
  factory MonthlyExpense.fromMap(Map <String, dynamic> map){
    return MonthlyExpense(
      id: map['expense_id'],
      expenseName: map['expense_name'], 
      expenseAmount: map['expense_amount'],
      expenseCategory: map['expense_category']
    );
  }

  //method to create a copy of the model with updated values
  MonthlyExpense copyWith({
    int? id,
    String? expenseName,
    String? expenseAmount,
    String? expenseCategory
  }) {
    return MonthlyExpense(
      id: id ?? this.id ,
      expenseName: expenseName ?? this.expenseName, 
      expenseAmount: expenseAmount ?? this.expenseAmount,
      expenseCategory: expenseCategory ?? this.expenseCategory
    );
  }
}