//model class for our monthly expense
//this will be used to represent the data in our app and to interact with the database

class MonthlyExpense{
  //the fields our monthly expense object will have
  final int? id;//id is nullable because it will be auto-generated by the database when we insert a new record
  final String name;
  final double amount;
  final String category;

  //constructor for the model in memory
  MonthlyExpense({
    this.id,
    required this.name,
    required this.amount,
    required this.category,
  });

  //method to convert the model to a map for storage in the database
  Map <String, dynamic> toMap() {
    return{
      'id' : id,
      'name' : name,
      'amount' : amount,
      'category' : category,
    };
  }

  //rebuild the model from a map retrieved from the database
  factory MonthlyExpense.fromMap(Map <String, dynamic> map){
    return MonthlyExpense(
      id: map['id'],
      name: map['name'],
      amount: (map['amount'] as num).toDouble(),
      category: map['category']
    );
  }

  //method to create a copy of the model with updated values
  MonthlyExpense copyWith({
    int? id,
    String? name,
    double? amount,
    String? category
  }) {
    return MonthlyExpense(
      id: id ?? this.id ,
      name: name ?? this.name,
      amount: amount ?? this.amount,
      category: category ?? this.category
    );
  }
}